apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: kafka-exporter
  name: kafka-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: kafka-exporter
        image: dfdsdk/kafka-exporter:0.1.1
        name: kafka-exporter
        env:
        - name: TOPIC_FILTER
          value: ".*"
        - name: GROUP_FILTER
          value: ".*"
        resources:
          limits:
            cpu: 400m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 64Mi
