apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: kafka-exporter
    scrape-service-metrics: "true"
  name: kafka-exporter
  namespace: grafana
spec:
  ports:
  - name: metrics
    port: 9308
    protocol: TCP
    targetPort: 9308
  selector:
    app: kafka-exporter
  type: ClusterIP
